version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /home/linuxvm/nodeapp/node_modules:/app/node_modules/
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /home/linuxvm/nodeapp/node_modules:/app/node_modules/
    command: ["npm", "run", "test"]
